name: Simple workflow

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 * * * *'


jobs:
  main_job:
    runs-on: unbuntu-latest

    steps:
      - name: Recuperation code source
        run: echo "Récupération du code source"

      - name: Verification
        run: echo "Vérification terminée"
